### PR TITLE
Add pages feature

### PR DESCRIPTION
**Pull request by AntoineInsa**
Let's merge it!

Coming from https://github.com/attendease/jekyll-attendease/pull/85

### CODE REVIEW

**Comment by pgib** [comment]
If we're absolutely sure we've done everything we need to do, then the version just needs to not be a pre-release.

**Comment by AntoineInsa** [comment]
I think we are not fully done, but could we still merge to master and open a new PR for later improvements?

**Comment by pgib** [comment]
Sure.

**Comment by AntoineInsa** [comment]
@pgib would you mind approving this PR then? Thanks!

**Comment by AntoineInsa** [comment]
Thank you!

**Pull request merged**
