### PR TITLE
Add safe_json filter and meta=true request

### PR DESCRIPTION
**Pull request by AntoineInsa**
Connect #75

The `safe_json` filter allows to safely output json strings in javascript code to be parsed later, without any errors. Non ascii-characters, as well as line jump characters are removed, inside/outside quotes are escaped.

Usage example
```javascript
<script type="text/javascript">
  Attendease.apiRoot    = '{{ site.attendease.api_host }}';
  // Load Attendease objects
  Attendease.presenters = JSON.parse("{{ site.attendease.presenters | safe_json }}");
  Attendease.venues     = JSON.parse("{{ site.attendease.venues     | safe_json }}");
  Attendease.rooms      = JSON.parse("{{ site.attendease.rooms      | safe_json }}");
  Attendease.filters    = JSON.parse("{{ site.attendease.filters    | safe_json }}");
  Attendease.sessions   = JSON.parse("{{ site.attendease.sessions   | safe_json }}");
  Attendease.instances = Attendease.sessions.map(function(session){
    return session.instances.map(function(instance){
      instance.session = session;
      return instance;
    })
  }).reduce(function(a, b) {
    return a.concat(b);
  }, []);
</script>
```

### CODE REVIEW

**Comment by AntoineInsa** [comment]
@eddanger tests are passing locally, but seem to fail on Travis. Any idea why?

```
> bundle exec rake
...
Finished in 1.19 seconds (files took 1.15 seconds to load)
51 examples, 0 failures, 1 pending
[Coveralls] Outside the CI environment, not sending data.
```

**Comment by eddanger** [comment]
The CI is failing but I don't see what changed to exclude `httparty` from the build.

Perhaps it needs to be explicitly added to the Gemfile? Not sure how it worked before!?

**Comment by eddanger** [comment]
Curious to know why `safe_json` was needed? Did `.to_json` miss something in the `json` filter?

**Comment by AntoineInsa** [comment]
It's all explained in the code. `\n were jumping lines in js, thus breaking the code, as well as non-ascii code such as the bullet point (http://www.fileformat.info/info/unicode/char/2022/index.htm). 

All of these characters were triggering errors, such as
```
Uncaught SyntaxError: missing ) after argument list
```
You can try yourself in the js console by putting
```
JSON.parse(" qsmldkfj
qsmdlkfj")
JSON.parse("{\"qsm\"dlkj\":\"qmsldkf\"}")
etc...
```

**Comment by eddanger** [comment]
Strange `.to_json should output a string like: `"{\"test\":\"first\\nsecond\"}"` which will work with `JSON.parse` in javascript.

Where were you seeing linebreaks that were not escaped?

Also I was able to do the following: `["bullet" => "•"].to_json` Then take that string run it in the javascript console in `JSON.parse()`.

The end-result is that the json we get from the API should always be valid.

Just trying to understand what happened that required this `safe_json` hack.

**Comment by AntoineInsa** [comment]
@eddanger The trick is to actually to use
```
puts obj.to_json
instead of
obj.to_json
```
because that's what the filter is doing. If you copy the result of the puts in the ruby console to the js console, does it still work?
Eventually, you want to have the full setup to understand well, and have the following PRs checkout locally:
jekyll-attendease: attendease/jekyll-attendease#76
attendease: #6486
attendease-third-party-themes: coverall/Attendease-Third-Party-Themes#1044

Then you can play with session titles or description. To be even closer to the reality, I'll advice you to run the following:
```
bundle exec rake org:esri:esri:import['Esri Federal GIS Conference (FedGIS)',fedgis,false,true]
```

**Comment by eddanger** [comment]
When I use the liquid filter on a data structure everything works as expected:

`{{ site.attendease.sessions | jsonify }}`

What are you seeing?

**Comment by AntoineInsa** [comment]
I didn't know that `jsonify` was built-in.
```
http://jekyllrb.com/docs/templates/ 
Data To JSON
Convert Hash or Array to JSON.
{{ site.data.projects | jsonify }}
```
But when I try
```
      Attendease.presenters = JSON.parse("{{ site.attendease.presenters | jsonify }}");
      Attendease.venues     = JSON.parse("{{ site.attendease.venues     | jsonify }}");
      Attendease.rooms      = JSON.parse("{{ site.attendease.rooms      | jsonify }}");
      Attendease.filters    = JSON.parse("{{ site.attendease.filters    | jsonify }}");
      Attendease.sessions   = JSON.parse("{{ site.attendease.sessions   | jsonify }}");
````
I get
```
Uncaught SyntaxError: missing ) after argument list
```
See source
welcome_-_esri_developer_summit

Have you actually tried with the real projects and PRs? Because for sure it works with simple date, but it's more complicated with real data (non asci, quotes, return carriage...)

Plus multiline string support is not really good, according to: http://stackoverflow.com/questions/805107/creating-multiline-strings-in-javascript

Any thoughts?

**Comment by eddanger** [comment]
It's already json so you don't need to parse it!

```
Attendease.sessions  = {{ site.attendease.sessions   | jsonify }};
```

**Comment by AntoineInsa** [comment]
Ahhhhhhh! Thanks for pointing that out! Encoding twice and parsing twice is actually more difficult that it sounds like!

It's working well now, thanks for your help, and sorry for the time I've taken from you. That is exactly why code reviews are good! Thank you!

Reference: https://docs.omniref.com/ruby/gems/jekyll/2.4.0/symbols/Jekyll::Filters/jsonify

**Comment by eddanger** [comment]
I was a bit confused too. I was racking my brains trying to figure out how it wasn't working!

**Pull request merged**
